name: fragfoldx
channels:
  - conda-forge
  - plotly
dependencies:
  - flake8
  - isort
  - black
  - pytest
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - seaborn
  - notebook
  - numpy<2
  - pandas
  - biopython>=1.80
  - openpyxl
  - pymol-open-source
  - plotly
  - pip:
    - python-dotenv
    - localcider
    - py3Dmol
    # - mkdocs
    # - logomaker
    - -e .
    # - -e ../a3mcat/
